### ISSUE TITLE
spec

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/tengo-tester#1]
```
$ tengo-tester run
```

.tengo-tester.yaml

```yaml
---
tests:
- name: ""
  script: foo.tengo
  params: {}
  tests:
  - name: ""
    script: |
      # tengo script to evaluate the result
  - name: ""
    test_file: foo_test.tengo
  - name: ""
    variable: ""
    equal: {}
```
