### ISSUE TITLE
fix yaml map's equality

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/tengo-tester#6]
```yaml
---
entries:
- name: main
  script_file: foo.tengo
  params: {}
  tests:
  - name: test
    var_name: result
    equal:
      foo: hello
```

foo.tengo

```
result := {
  foo: "hello"
}
```

```
$ tengo-tester run
test fails
entry_name: main
test_name: test
the value of the variable result is unexpected (-want, +got)
interface{}(
-       map[interface{}]interface{}{string("foo"): string("hello")},
+       map[string]interface{}{"foo": string("hello")},
  )
entry fails
entry_name: main

FATA[0000]
```
