### ISSUE TITLE
int != int64

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/tengo-tester#8]
.tengo-tester.yaml

```yaml
---
entries:
- name: main
  script_file: hello_world.tengo
  tests:
  - name: test
    var_name: result
    equal: 1
```

hello_world.tengo

```
result := 1
```

```
$ tengo-tester run
test fails
entry_name: main
test_name: test
the value of the variable result is unexpected (-want, +got)
interface{}(
-       int(1),
+       int64(1),
  )
entry fails
entry_name: main

FATA[0000]
```
